### PR TITLE
Fix crashes with .zero initial values for start & end Frame

### PR DESCRIPTION
**Pull request by alexookah**
related to this PL: https://github.com/Daltron/NotificationBanner/pull/363 which should fix all crashes

### CODE REVIEW

**Comment by alexookah** [comment]
@Daltron

**Review by Daltron — CHANGES_REQUESTED** [review]
Does this actually compile? It should be this shouldn't it?

```swift
private(set) var startFrame: CGRect = .zero
private(set) var  endFrame: CGRect = .zero
```

**Comment by alexookah** [comment]
Hello @Daltron 
You are right. Sorry I didn't try to compile it.
Should be fine now

**Comment by Daltron** [comment]
Thanks for doing this @alexookah!

**Pull request merged**
