### PR TITLE
#231 swift package manager support

### PR DESCRIPTION
**Pull request by lvnkmn**
As aftercare for #231 I have

- Made sure the `MarqueeLabel` will still work when their `xcode11` branch is deleted**
- `NotificationBanner` doesn't get compiler errors when added using SPM***

**  The`xcode11` was merged to master, but that code has not been released yet. As soon as that is done, it will be a good idea to start relying on the sementic versions instead of branch names. I'll keep an eye one the MarqueeLabel repo and will try to do this when it starts to become possible.

***  SPM is a bit more strict than cocoapods when it comes to imports, `import foundation` caused the UIKit code to be unknown.

### CODE REVIEW

**Comment by lvnkmn** [comment]
Update (b9d9e7e):
All dependencies rely on released versions now. Merging this PR should make `NotificationBanner` completely future proof in terms of Swift package manager, also it's recommended since `MarqueeLabel`s branch that's currently used may introduce breaking changes.

**Comment by pcmanik** [comment]
@Daltron can you merge this please?

**Comment by Daltron** [comment]
Thanks for doing this @lvnkmn!

**Comment by lvnkmn** [comment]
You’re welcome 🙂

**Pull request merged**
