### PR TITLE
Updates swift 4.2 syntax

### PR DESCRIPTION
**Pull request by spadafiva**
@Daltron I've done the language updates required for updating to swift 4.2.  I didn't update the podspec or cartfile at all.  Hopefully this helps!

### CODE REVIEW

**Comment by spadafiva** [comment]
@Daltron Can you give me a heads up when you get the podfile updated so that I can update my project? :)

**Comment by Daltron** [comment]
Hi @spadafiva! 😄 Thanks for doing this! I seem to be running into some issues. Are you able to actually get this able to compile on xCode10? I'm seeing the following errors when compiling, thus I'm unable to upload a pod version.

screen shot 2018-09-14 at 1 49 15 pm

**Comment by spadafiva** [comment]
@Daltron I didn't get those when compiling.  I'll pull what you've got and take a look

**Comment by spadafiva** [comment]
@Daltron Did you try cleaning before building?

**Comment by Daltron** [comment]
@spadafiva I had to change my `Swift Language Version` flag in my xCode project to `Swift 4.2`. That resolved that issue but I ran into another one. When I'm pushing up to Cocoapods, its not using Swift 4.2 to build, thus it is failing.

**Comment by spadafiva** [comment]
@Daltron You can fix that by changing the command line tools to use xcode 10 instead of 9.4 I think?

**Comment by spadafiva** [comment]
Otherwise, in one of the podspecs I was updating, I added `s.swift_version = '4.2'`, which may be the issue

**Pull request merged**
