### PR TITLE
Allow custom dismiss duration

### PR DESCRIPTION
**Pull request by V-FEXrt**

### CODE REVIEW

**Comment by Daltron** [comment]
Hi @V-FEXrt ! 😄 Thanks for doing this! This change is now pushed to the `1.6.3` CocoaPods release!

**Comment by V-FEXrt** [comment]
@Daltron Thanks for the quick merge! =)

**Comment by V-FEXrt** [comment]
If you ever have small things you need done here feel free to ping me and I'll help when I can

**Comment by Daltron** [comment]
@V-FEXrt Sounds great, thank you! 👍

**Pull request merged**
