### PR TITLE
Add support for Swipe Down Gesture

### PR DESCRIPTION
**Pull request by MaG21**
This commit addresses issue #72, it adds support to detect whenever a user
swipes down a banner.

### CODE REVIEW

**Comment by Daltron** [comment]
Hi @MaG21! 😄 First off, thanks for doing this. This all look good but I would like ONE more thing before I merge it! I don't personally feel like swiping down on a banner that is at the top should dismiss it. Only when your swipe goes against the banner should it be dismissed. If you could add that in, I'd be more than happy to merge this!

**Comment by JoniVR** [comment]
I agree with this, swiping down to dismiss feels very counter-intuitive.

**Comment by MaG21** [comment]
@Daltron I'll check and update.

@JoniVR it makes sense if the banner is located at the bottom ie `banner.show(bannerPosition: .bottom)`

**Comment by JoniVR** [comment]
@MaG21 you’re right, from the bottom it makes sense, my bad. Nice 👍🏻

**Comment by MaG21** [comment]
Sorry guys, I've will make this PR properly. Will decline this one and do another PR.

**Pull request closed without merging**
