### PR TITLE
V146

### PR DESCRIPTION
**Pull request by YauheniYarotski**
connect NotificationBannerUtilities

### CODE REVIEW

**Comment by Daltron** [comment]
@YauheniYarotski Please resolve all merge conflicts and then I can merge 😄

**Comment by YauheniYarotski** [comment]
@Daltron done, but please check the diff of pod spec file: s.version          = '1.5.1'
It's for 1.4.6 version.

**Comment by Daltron** [comment]
@YauheniYarotski thanks for fixing! 😄  The pod spec version doesn't matter in this instance. I will have to push a new pod in order for these changes to take affect unless you are pointing directly to the master branch. You are using Carthage though correct?

**Comment by Daltron** [comment]
Closes #68 🎉

**Comment by Daltron** [comment]
@YauheniYarotski I just release a v1.5.2 to CocoaPods if you are using CocoaPods.

**Pull request merged**
