### PR TITLE
Target SnapKit Version 5.6.0

### PR DESCRIPTION
**Pull request by Baranets**
- SnapKit updated to the version 5.6.0 (CocoaPods, Carthage and SPM)

### CODE REVIEW

**Review by ShenYj — COMMENTED** [review]
I'm preparing to upgrade SnapKit to 5.6 from 5.0.1

**Comment by ShenYj** [comment]
It seems that many of the changes you committed are unnecessary

**Comment by ShenYj** [comment]
I request a new PR with less file change #391

**Comment by Daltron** [comment]
Closing due to #392 being merged in.

**Pull request closed without merging**
