### PR TITLE
Banner top inset fix for dynamic island

### PR DESCRIPTION
**Pull request by Maxim-Inv**

### CODE REVIEW

**Comment by Daltron** [comment]
@Maxim-Inv I really appreciate you doing this! Before I can merge it in, it looks like a few banners are not quite adjusting correctly for the dynamic island. I would recommend going down the line in the example app and making sure all of those work as expected. Could you take a look please? I'll get this merged in asap once we can confirm that all cases have been fixed!

Thank you!! 🙂 🥇 

Simulator Screen Shot - iPhone 14 Pro - 2022-09-21 at 09 55 59

**Comment by Maxim-Inv** [comment]
Ok. I'll try to make it on weekends.

**Comment by sayler8182** [comment]
Hi, did you manage to fix this ?

**Comment by Maxim-Inv** [comment]
Sorry I haven't had time yet

**Comment by Roger-Blinto** [comment]
A fix and merge of this would be much appreciated.

**Comment by Daltron** [comment]
Going to close this as this should be fixed now that #399 has been merged in.

**Pull request closed without merging**
