### PR TITLE
Array bounds check before removal

### PR DESCRIPTION
**Pull request by shanev**
Added bounds check to fix crash when banners is 0.

### CODE REVIEW

**Comment by Daltron** [comment]
Hey @shanev! 👍  I assume this crash was happening to you? Is this happening when you decide not to place a banner on the queue? If not, then I don't understand why this crash would be happening. The `showNext()` method in the `NotificationBannerQueue` class is called directly after a banner is dismissed. Thus, the `banners.remove(at: 0)` will never fail because there will always be a banner on the queue if this statement is hit.

**Comment by shanev** [comment]
It happens when I'm debugging and stepping through code that happens to show a banner. I haven't looked through the source in detail to find out why it happens, but doing the bounds check stops the crash for me.

**Comment by Daltron** [comment]
@shanev Thanks for this!

**Comment by Daltron** [comment]
@shanev @leiguang CocoaPods version [v1.3.3](https://github.com/Daltron/NotificationBanner/releases/tag/1.3.0) has been released and fixes this issue!

**Pull request merged**
