### PR TITLE
'delegate' methods are not fired - issue 121

### PR DESCRIPTION
**Pull request by Hassaniiii**
`notificationBannerDidAppear` and `notificationBannerDidDisappear` methods are not fired. They are called within `UIView.anmate` completion closure and the `delegate` instance in **BaseNotificationBanner.swift** gets nil.

### CODE REVIEW

**Comment by Daltron** [comment]
Hi @Hassaniiii! Could you provide a code example where the delegate methods are not getting fired please? I just ran a test and everything seems to be working as expected. It sounds like your delegate's reference count is zero which would in return cause it to go nil

**Comment by Hassaniiii** [comment]
I used it in the following code. Indeed, the only function that had been fired was `func notificationBannerWillAppear(_ banner: BaseNotificationBanner)`  and other ones all had not. When I used the debugger to address the problem, I found out that the delegate instance got nil in `UIView.animate` completion. So, I decided to fix the issue by forking and making a pull request. Now, it is working as intended.

```swift
class AlertControlCenter: NSObject {
    private var completion: AlertCompletion?
    
    public func success(_ title: String, body: String = "", completion: AlertCompletion) {
        self.completion = completion
        self.show(title, body, .success)
    }    
}

extension AlertControlCenter {
    private func show(_ title: String, _ body: String, _ style: BannerStyle) {
        let banner = NotificationBanner(title: title, subtitle: body, style: style)
        self.setupBanner(banner)
        self.setupLabels(banner)
        banner.delegate = self
        
        banner.show(bannerPosition: .top)
    }
}

extension AlertControlCenter: NotificationBannerDelegate {
    func notificationBannerWillAppear(_ banner: BaseNotificationBanner) {}
    
    func notificationBannerDidAppear(_ banner: BaseNotificationBanner) {}
    
    func notificationBannerWillDisappear(_ banner: BaseNotificationBanner) {}
    
    func notificationBannerDidDisappear(_ banner: BaseNotificationBanner) {
        self.completion??()
    }
}
```

**Comment by Daltron** [comment]
@Hassaniiii If the delegate instance is nil, that means your `AlertControlCenter` object doesn't have any references holding on to it. This is how ARC works and appears to be a non issue. I would suggest maybe making your `AlertControlCenter` a singleton object that way it is guaranteed to never get deinitialized.

**Comment by Hassaniiii** [comment]
Yes, this is what ARC actually does. It applies on instances which means that the `BaseNotificationBanner`'s `delegate` instance should be defined as a strong variable so ARC won't dealloc it. By looking at my code, the `AlertControlCenter` instance is defined as a strong variable as well. 
In addition, the structure of different project may vary, e.g. I don't use singleton for `AlertControlCenter` since it is not needed as well as singleton is not a recommended pattern for all problems.

**Comment by Daltron** [comment]
@Hassaniiii delegates should almost always be defined as weak variables. I actually can't think of a good situation where you would want to not make a delegate instance weak. I'm going to close this as I don't think this is a problem within NotificationBanner itself.

**Pull request closed without merging**
