### PR TITLE
Use sizing methods on UILabel to determine text size for GrowingNotificationBanner

### PR DESCRIPTION
**Pull request by petrpavlik**
It provides more flexibility, such as being able to limit the number of lines of title/subtitle.

### CODE REVIEW

**Comment by Daltron** [comment]
Thanks @petrpavlik, this can be found in the latest CocoaPods release!

**Comment by Daltron** [comment]
Something is wrong with CocoaPods that is preventing me from pushing a new release. I will try again later in the day to see if the issue is resolved.

**Comment by Daltron** [comment]
This can be found in the `2.2.2` release!

**Comment by petrpavlik** [comment]
Awesome, thanks!

**Pull request merged**
