### PR TITLE
Banner Configuration Struct initialization

### PR DESCRIPTION
**Pull request by ahartwel**

### CODE REVIEW

**Comment by ahartwel** [comment]
Hey Daltron,
I implemented the creation of the banner with a configuration struct. I kept the original api in place but switched them over to using the struct under the hood and added an initializer `init(config: BannerConfiguration)`

The configurations have two inits, one long one with all the properties (with some default values) and a builder init.
```swift
//long init
            let config = BannerConfiguration(color: UIColor.green, title: "Custom Notification from a struct", attributedTitle: nil, subtitle: "Extremely Customizable", attributedSubtitle: nil, leftView: nil, rightView: nil, customView: nil, bannerHeight: 100, duration: 2)


//builder 
let config = BannerConfiguration(builder: { banner in
                banner.color = UIColor.green
                banner.title = "Custom notification from a struct"
                banner.subtitle = "Extremely Customizable"
                banner.bannerHeight = 100
                banner.duration = 2
    })

```

**Comment by Daltron** [comment]
@ahartwel First off, thanks a lot for taking a stab at this. It looks like a lot of time was put into it and that is greatly appreciated. However, after carefully reviewing, I'm still not sure this is in NotificationBanner's best interest quite yet. It doesn't really seem to add any new significant functionality that NotificationBanner doesn't already have. I'd love to hear any opposition you may have. I encourage you to use your forked version if it truly suits your needs better.

**Comment by ahartwel** [comment]
It didn't add any functionality but it allows users to customize the banner without needing to know about the internals of the banner. The best example of this is the duration and height. In master you have to read through the code to find out they are publicly modifiable. With a config object you get all the properties abstracted away from their implementation and you can set what you want and just ignore the inner workings of the banner. You don't need to read through any docs or code to know what you can do.

**Comment by Daltron** [comment]
@ahartwel I understand the point you are trying to bring across but I still don't think this configuration option makes setting the `duration` and `bannerHeight` and other properties for that matter easier. The chances are very high (but you may disagree) that someone who wants to modify these properties are simply going to:

1. Type `banner.dur` and `banner.hei` and see from xCode's auto-complete that the `duration` and `bannerHeight` properties are available. This option is how I and a lot of other developers I know quickly see if properties are available within a library.

or

2. If they can't find what they are looking for via xCode's auto complete, then quickly glance over the source code to see if the property they are looking for can be modified.

**Pull request closed without merging**
