### PR TITLE
Add PrivacyInfo file

### LINKED ISSUE #429: Request for updated iOS SDK version with the xcprivacy manifest
Subject: We need to incorporate the xcprivacy manifest into our app . Starting March 13, Apple will send notifications when uploading builds to the App Store, and this will become mandatory from May 1. All the SDKs used in our app needs to incorporate the xcprivacy manifest.
Reference: https://developer.apple.com/news/?id=3d8a9yyh

Actions needed: We need the compatible xcprivacy manifest version IOS SDK with xcprivacy manifest. We are expecting a seamless upgrade by upgrading to the latest version.

### PR DESCRIPTION
**Pull request by chickdan**
I just saw the conversation in #429 this morning and was updating #426 when you merged it, this should be the last piece required for the privacy manifest requirements 🙂

closes #429

### CODE REVIEW

**Comment by Daltron** [comment]
@chickdan is this ready to be merged or is it still a draft?

**Comment by chickdan** [comment]
@Daltron it's still in draft, I'm getting an error when attempting to import with SPM so I'm looking into that.

**Comment by chickdan** [comment]
I'm opening it for review, I can import with SPM and CocoaPods. However, this isn't set up like most libraries so I'm not sure if more work is needed.

**Comment by Daltron** [comment]
I know very little about this requirement so I am going to take your word for it!

**Pull request merged**
