### PR TITLE
Fixed calculation of window size after device orientation changed.

### PR DESCRIPTION
**Pull request by luximetr**
Fixed calculation of window size after device orientation changed.

### CODE REVIEW

**Comment by Daltron** [comment]
@luximetr Can you move these to a `UIWindowExtension` class and make them calculated variables instead of functions please?

**Comment by luximetr** [comment]
ok
13 марта 2019 г., 20:27 +0200, Dalton Hinterscher <notifications@github.com>, писал:

**Comment by luximetr** [comment]
I changed it as you said.

**Comment by Daltron** [comment]
I don't think this is the proper way to do this. I believe you need to be using `UIApplication.shared.statusBarOrientation`

**Pull request closed without merging**
