### PR TITLE
navigationBarHidden & iPhoneX Update

### PR DESCRIPTION
**Pull request by pikachu987**
Adding navigationController.setNavigationBarHidden (true, animated: false)
In iPhoneX, the height of Banner decreases.

In the BaseNotificationBanner.swift class, in the updateSpacerViewHeight and shouldAdjustForIphoneX methods
We have changed parentViewController == nil to this (parentViewController? .navigationController? .isNavigationBarHidden ?? true).

### CODE REVIEW

**Comment by Daltron** [comment]
Hi @pikachu987! 😄 Can you add pictures to this PR so I can better understand what you are talking about please?

**Comment by pikachu987** [comment]
kakaotalk_2017-12-19-23-18-27_photo_91

The height of the banner on the iPhoneX is strange.

**Comment by Daltron** [comment]
@pikachu987 and can you also show me a picture of what it looks like after your PR changes? I should be able to test this out within the next couple days or so.

**Comment by pikachu987** [comment]
kakaotalk_2017-12-20-00-19-41_photo_63

When the NavigationBar is not Hidden, everything works fine.
And everything works fine even when it is not iPhoneX.
The problem only occurs when the NavigationBar is Hidden and iPhoneX.
The above picture is a picture after solving the problem.

**Comment by Daltron** [comment]
@pikachu987 Perfect. I actually had a few minutes to test and everything seemed to be ok. I'll merge now and create a new CocoaPods release in just a few minutes. Thanks!

**Comment by Daltron** [comment]
@pikachu987 Fixed in v1.5.3 release! 🎉 Thanks again! 👍

**Comment by pikachu987** [comment]
I also received a lot of help from your open source. Thank you. 👍

**Pull request merged**
