### PR TITLE
Feature/314 add a11y support

### PR DESCRIPTION
**Pull request by misteu**
This Pull request solves: https://github.com/Daltron/NotificationBanner/issues/314

**What this does:**

Whenever a Banner is shown, a `UIAccessibility.Notification` will be posted now to make sure that users with enabled VoiceOver will be notified about the banner. It will read the banners `title` and its `subtitle`.

**How to test?**

Enable VoiceOver and trigger a banner.

Here is an example .mov video of the implementation.
[a11y_banner.mov.zip](https://github.com/Daltron/NotificationBanner/files/5380588/a11y_banner.mov.zip)

### CODE REVIEW

**Comment by misteu** [comment]
Dear maintainers,
would be great if you could label this PR with: `hacktoberfest-accepted` 👍

**Comment by Daltron** [comment]
@misteu can you please fix the indentation issues with this PR and resubmit? Thanks!

**Comment by misteu** [comment]
Hi,
yes I will do that later today 👍

**Comment by misteu** [comment]
@Daltron I fixed the indentation for this MR.

**Comment by Daltron** [comment]
Thanks for doing this @misteu!!

**Pull request merged**
