### PR TITLE
Display several banners stacked

### PR DESCRIPTION
**Pull request by mrsnow-git**
Implement possibility to display several banners on screen simultaneously with animations calculations, taps for dismiss and in-process banners showing.

In current version it allow to display several banners at once (number of banners can be setup), from top (or bottom), one under another, with stacked animation.

Also added option to close the banner with the tap on it.

There is the screen capture of its working in our app:

Sep-06-2019 09-49-00

It's already used in this state in our app for 6-7 month. I just updated it to main lib latest version.

### CODE REVIEW

**Comment by Daltron** [comment]
Woah! This looks really cool! Could you update the example project to include this type of stacked behavior? I plan on reviewing this in the next couple days.

**Comment by mrsnow-git** [comment]
yes, sure, will add example for this and snippet to usage section in read me. I'll take 2-3 days before I can do it, right now don't have enough time.

**Comment by mrsnow-git** [comment]
I'm done with examples update, fix some things, added more info to README

**Comment by Daltron** [comment]
REALLY excellent work! 👍

**Pull request merged**
