### PR TITLE
setting custom colors for the default banner styles

### PR DESCRIPTION
**Pull request by ahartwel**
Hey, awesome library. I was looking through it and thought it would be cool to be able to set your own colors for the default Banner Styles outside of setting the background color directly. Here is a stab at making that possible.

### CODE REVIEW

**Comment by ahartwel** [comment]
I also think it would be interesting to add custom fonts in the same way. That way it would be super easy to  customize the default style without having to push in custom views

**Comment by Daltron** [comment]
Hi @ahartwel! Thanks for making the effort to contribute. After looking over the PR, I don't quite understand what it accomplishes as `color` is a get only property in your modification. If we are wanting to be able to set custom background colors for the predefined styles, I think the better way to go about this would be to make the `BannerStyle` a struct that accepts a color in its init method. In the same way, we should be able to modify the color on existing styles by overriding the color property.

**Comment by ahartwel** [comment]
@Daltron 
It's a get only property but the default value is defined as an extension of the protocol not the BannerStyle struct. That way you can create a BannerStyle extension and effectively override the getter of color. You could create a BannerStyles.swift file in your project, not the pod and add something like this.

```swift
extension BannerStyle {
	var color: UIColor {
		switch self.type {
			case .danger: return UIColor.red;
    		case .info: return UIColor.yellow;
    		case .none: return UIColor.white;
    		case .success: return UIColor.green;
    		case .warning: return UIColor.orange;
		}
	}
}

```

Then when the color property is read it will return the colors you defined, not the default values.

**Comment by Daltron** [comment]
@ahartwel Ok I see what you are trying to accomplish. However, you will be unable to create a custom styles file like you mentioned because you would receive an `invalid redecleration` of the `color` property because an extension with the `color` property already exists in the pod.

**Comment by ahartwel** [comment]
I've run it, it compiles and sets the color properly. You don't run into the invalid redeclaration because you never declared the value inside of the struct, just the protocol. Here is the ExampleViewController.swift I was working with.

```
//
//  ViewController.swift
//  NotificationBanner
//
//  Created by Daltron on 03/18/2017.
//  Copyright (c) 2017 Daltron. All rights reserved.
//

import UIKit
import NotificationBanner

extension BannerStyle {
    public var color: UIColor {
        return UIColor.blue
    }
}


class ExampleViewController: UIViewController {
    
    private var exampleView: ExampleView!
    
    init() {
        super.init(nibName: nil, bundle: nil)
        edgesForExtendedLayout = UIRectEdge()
        exampleView = ExampleView(delegate: self)
        view = exampleView
        title = "Notification Banner"
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    func selectedQueuePosition() -> QueuePosition {
        let selectedIndex = exampleView.segmentedControl.selectedSegmentIndex
        return selectedIndex == 0 ? .front : .back
    }

}


extension ExampleViewController : ExampleViewDelegate {
    
    func basicNotificationCellSelected(at index: Int) {
        switch index {
        case 0:
            // Basic Success Notification
            let banner = NotificationBanner(title: "Basic Success Notification",
                                            subtitle: "Extremely Customizable!",
                                            style: .success)
            banner.onTap = {
                self.showAlert(title: "Basic Success Notification Tapped")
            }
            
            banner.show(queuePosition: selectedQueuePosition())
        case 1:
            // Basic Danger Notification
            let banner = NotificationBanner(title: "Basic Danger Notification",
                                            subtitle: "Extremely Customizable!",
                                            style: .danger)
            banner.show(queuePosition: selectedQueuePosition())
        case 2:
            //Basic Info Notification
            let banner = NotificationBanner(title: "Basic Info Notification",
                                            subtitle: "Extremely Customizable!",
                                            style: .info)
            banner.show(queuePosition: selectedQueuePosition())
        case 3:
            // Basic Warning Notification
            let banner = NotificationBanner(title: "Basic Warning Notification",
                                            subtitle: "Extremely Customizable!",
                                            style: .warning)
            banner.show(queuePosition: selectedQueuePosition())
        default:
            return
        }
    }
    
    func basicNotificationCellWithSideViewsSelected(at index: Int) {
        switch index {
        case 0:
            // Success Notification with Left View
            let leftView = UIImageView(image: #imageLiteral(resourceName: "success"))
            let banner = NotificationBanner(title: "Success Notification", subtitle: "This notification has a left view!", leftView: leftView, style: .success)
            banner.show(queuePosition: selectedQueuePosition())
        case 1:
            // Danger Notification with Right View
            let rightView = UIImageView(image: #imageLiteral(resourceName: "danger"))
            let banner = NotificationBanner(title: "Danger Notification", subtitle: "This notification has a right view!", rightView: rightView, style: .danger)
            banner.show(queuePosition: selectedQueuePosition())
        case 2:
            // Info Notification with Left and Right Views
            let leftView = UIImageView(image: #imageLiteral(resourceName: "info"))
            let rightView = UIImageView(image: #imageLiteral(resourceName: "right_chevron"))
            let banner = NotificationBanner(title: "Info Notification", subtitle: "This notification has two side views!", leftView: leftView, rightView: rightView, style: .info)
            banner.show(queuePosition: selectedQueuePosition())
        default:
            return
        }
    }
    
    func basicCustomNotificationCellSelected(at index: Int) {
        switch index {
        case 0:
            // Tarheels Completely Custom Notification
            let banner = NotificationBanner(customView: NorthCarolinaBannerView())
            banner.show(queuePosition: selectedQueuePosition())
        default:
            return
        }
    }
    
    func basicStatusBarNotificationCellSelected(at index: Int) {
        switch index {
        case 0:
            // Status Bar Success Notification
            let banner = StatusBarNotificationBanner(title: "Success Status Bar Notification", style: .success)
            banner.show(queuePosition: selectedQueuePosition())
        case 1:
            // Status Bar Danger Notification
            let banner = StatusBarNotificationBanner(title: "Danger Status Bar Notification", style: .danger)
            banner.show(queuePosition: selectedQueuePosition())
        case 2:
            // Status Bar Info Notification
            let banner = StatusBarNotificationBanner(title: "Info Status Bar Notification", style: .info)
            banner.show(queuePosition: selectedQueuePosition())
        case 3:
            // Status Bar Warning Notification
            let banner = StatusBarNotificationBanner(title: "Warning Status Bar Notification", style: .warning)
            banner.show(queuePosition: selectedQueuePosition())
        case 4:
            // Status Bar Attributed Title Notification
            let title = "Custom Status Bar Notification"
            let attributedTitle = NSMutableAttributedString(string: title)
            attributedTitle.addAttribute(NSForegroundColorAttributeName,
                                         value: UIColor.red,
                                         range: (title as NSString).range(of: "Custom"))
            attributedTitle.addAttribute(NSForegroundColorAttributeName,
                                         value: UIColor.cyan,
                                         range: (title as NSString).range(of: "Status"))
            attributedTitle.addAttribute(NSForegroundColorAttributeName,
                                         value: UIColor.green,
                                         range: (title as NSString).range(of: "Bar"))
            attributedTitle.addAttribute(NSForegroundColorAttributeName,
                                         value: UIColor.orange,
                                         range: (title as NSString).range(of: "Notification"))
            let banner = StatusBarNotificationBanner(attributedTitle: attributedTitle)
            banner.backgroundColor = UIColor(red:0.54, green:0.40, blue:0.54, alpha:1.00)
            banner.show(queuePosition: selectedQueuePosition())
        default:
            return
        }
    }
    
    func numberOfCells(for section: Int) -> Int {
        switch section {
        case 0:
            return 4
        case 1:
            return 3
        case 2:
            return 1
        case 3:
            return 5
        default:
            return 0
        }
    }
    
    func notificationBannerTitle(for section: Int) -> String {
        switch section {
        case 0:
            return "Basic Notification Banners"
        case 1:
            return "Notification Banners with Side Views"
        case 2:
            return "Notification Banner with Custom View"
        case 3:
            return "Status Bar Notifications"
        default:
            return ""
        }
    }
    
    func blockColor(at indexPath: IndexPath) -> UIColor {
        switch indexPath.row {
        case 0:
            return UIColor(red:0.22, green:0.80, blue:0.46, alpha:1.00)
        case 1:
            return UIColor(red:0.90, green:0.31, blue:0.26, alpha:1.00)
        case 2:
            return UIColor(red:0.23, green:0.60, blue:0.85, alpha:1.00)
        case 3:
            return UIColor(red:1.00, green:0.66, blue:0.16, alpha:1.00)
        default:
            return UIColor(red:0.54, green:0.40, blue:0.54, alpha:1.00)
        }
    }
    
    func notificationTitles(at indexPath: IndexPath) -> (String, String?) {
        if indexPath.section == 0 {
            switch indexPath.row {
                case 0:
                    return ("Basic Success Notification", nil)
                case 1:
                    return ("Basic Danger Notification", nil)
                case 2:
                    return ("Basic Info Notification", nil)
                case 3:
                    return ("Basic Warning Notification", nil)
            default:
                return ("", nil)
            }
        } else if indexPath.section == 1 {
            switch indexPath.row {
            case 0:
                return ("Success Notification", "With Left View")
            case 1:
                return ("Danger Notification", "With Right View")
            case 2:
                return ("Info Notification", "With Left and Right Views")
            default:
                return ("", nil)
            }
        } else if indexPath.section == 2 {
            switch indexPath.row {
            case 0:
                return ("Tarheels Notification", "Completely Custom")
            default:
                return ("", nil)
            }
            
        } else if indexPath.section == 3 {
            switch indexPath.row {
            case 0:
                return ("Success Notification", nil)
            case 1:
                return ("Danger Notification", nil)
            case 2:
                return ("Info Notification", nil)
            case 3:
                return ("Warning Notification", nil)
            case 4:
                return ("Custom Notification", nil)
            default:
                return ("", nil)
            }
        }
        
        return ("", nil)
    }
    
    func notificationImage(at indexPath: IndexPath) -> UIImage? {
        if indexPath.section == 2 {
            switch indexPath.row {
            case 0:
                return #imageLiteral(resourceName: "unc_logo")
            default:
                return nil
            }
        }
        
        return nil
    }
    
    func showAlert(title: String) {
        let alertController = UIAlertController(title: title, message: nil, preferredStyle: .alert)
        let action = UIAlertAction(title: "Ok", style: .default, handler: nil)
        alertController.addAction(action)
        present(alertController, animated: true, completion: nil)
    }
    
}


```

**Comment by Daltron** [comment]
@ahartwel I see that it compiles but I don't think I want NotificationBanner to go down this route. With this route, you would have to create an extension in each view controller (that isn't subclassed from a view controller that already has the extension implemented) and do the overriding. Like I mentioned, I think the struct/class route is the much cleaner way to go and will be easier to use for the user.

**Comment by ahartwel** [comment]
@Daltron You wouldn't need to create an extension for every view controller, it is global, it is attached to the BannerStyle struct not the view controller. But fair enough, I agree the struct/class route is clean :) I liked the idea of creating the banner with a warning level enum and wanted to try extending that.

**Comment by Daltron** [comment]
@ahartwel Thanks for correcting me on the wrong assumption. Since we both can agree that the struct/class route is cleaner, lets try implementing it that way. If you are interested in doing this, I'd be glad to make this a part of notification banner. If not, then I can add it the next set of features for the next release! 😃

**Comment by ahartwel** [comment]
@daltron yeah I'm down to implement it, excited to help out!

**Comment by Daltron** [comment]
@ahartwel Sounds great. I'll be on the lookout!

**Comment by Daltron** [comment]
@ahartwel I have implemented this in Release v1.1.0. Feel free to check it out!

**Pull request closed without merging**
